### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by GiannisMitr** [WURFL/wurfl-cloud-client-java#15]
Hello

The default connection to wurfl service is unencrypted carrying as Authorization header the api key (encoded with base64). I saw that the wurfl.configuration has no property for enabling https connection but the url: _https://api.wurflcloud.com/v1/json/search:('')_ supports it. Since the api key is subscription based and the chance of someone eavesdropping exists, shouldn't the client support that?

Thanks

**Comment by paulborile** [comment]
Yes, we should be using `https` in https://github.com/WURFL/wurfl-cloud-client-java/blob/master/code/src/main/java/com/scientiamobile/wurflcloud/utils/Constants.java#L61 by default. Feel free to change that in your running version, we'll be releasing a modified version soon.

**Comment by GiannisMitr** [comment]
Thank you for your response.

I cannot see how I can change that in my running version. I am using the _CloudClient_ and despite it implements constants interface I see that the API_TYPE used for the call is hardcoded in private buildRequestURL() method.

**Comment by paulborile** [comment]
Ok, we'll be releaseing a modified version in a short time. In the mean time you can fork this repo and make the change from http to https : is that a viable solution for you ?

**Comment by GiannisMitr** [comment]
Ok, thank you

**Comment by paulborile** [comment]
New version released with default to HTTPS.
